name: caiman
channels:
  - bioconda
  - conda-forge
dependencies:
  - caiman
  - pip
  - pip:
    - aiohttp
    - av
    - blinker
    - Brotli
    - cached-property
    - caiman
    - colorama
    - exceptiongroup
    - fqdn
    - h2
    - holoviews
    - imagecodecs
    - importlib_resources
    - ipyparallel
    - isoduration
    - jsonpointer
    - jupyter
    - jupyter_bokeh
    - kaleido~=0.2.1
    - msgpack
    - munkres~=1.1.4
    - mypy
    - napari~=0.5.4
    - nose
    - opencv-python~=4.9.0
    - opencv-python-headless~=4.9.0
    - PeakUtils
    - pickleshare
    - PIMS
    - pingouin~=0.5.5
    - pipdeptree~=2.25.0
    - pkgutil_resolve_name
    - plotly~=5.24.1
    - pooch~=1.8.2
    - pyconify~=0.1.6
    - PyJWT
    - pynwb
    - pyOpenSSL
    - pyqtgraph
    - PySide6~=6.7.2
    - PySocks
    - pyu2f
    - PyWavelets~=1.7.0
    - shiboken6~=6.7.2
    - tensorflow
    - tomli
    - typing-utils
    - unicodedata2
    - uri-template
    - webcolors
    - wheel~=0.45.1
    - zarr
    - zstandard~=0.23.0
    - 
